site_name: Powerlevel10k Documentation
repo_url: https://github.com/romkatv/powerlevel10k
edit_uri: null
nav:
  - Home: index.md
  - Get Started: getting_started.md
  - Features:
      - 'Configuration wizard': 'features/wizard.md'
      - 'Uncompromising performance': 'features/uncompromising_performance.md'
      - 'Powerlevel10k Compatibility': 'features/p10k_compatibility.md'
      - 'Pure compatibility': 'features/pure_compatibility.md'
      - 'Instant prompt': 'features/instant_prompt.md'
      - 'Show on command': 'features/show_on_command.md'
      - 'Transient prompt': 'features/transient_prompt.md'
