site_name: Powerlevel10k
repo_url: https://github.com/romkatv/powerlevel10k
theme:
  name: mkdocs
  nav_style: dark
  highlightjs: true
  hljs_style: atom-one-dark
  hljs_languages:
    - bash
    - zsh
    - sh
    - yaml
docs_dir: mkdocs
nav:
  - Home: index.md
  - Get Started: installation.md
  - Features:
      - 'Configuration wizard': 'features/wizard.md'
      - 'Uncompromising performance': 'features/uncompromising_performance.md'
      - 'Powerlevel9k Compatibility': 'features/p9k_compatibility.md'
      - 'Pure compatibility': 'features/pure_compatibility.md'
      - 'Instant prompt': 'features/instant_prompt.md'
      - 'Show on command': 'features/show_on_command.md'
      - 'Transient prompt': 'features/transient_prompt.md'
      - 'Current Directory that just works': 'features/current_directory.md'
      - 'Extremely Customizable': 'features/customizable.md'
      - 'Batteries included': 'features/batteries_included.md'
      - 'Extensible': 'features/extensible.md'
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md
