name: Deploy Powerlevel10k Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Install Mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - name: Deploy docs
        run: python -m mkdocs gh-deploy
