name: Deploy Powerlevel10k Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Mkdocs
        run: |
          python3 -m pip install --upgrade pip
          pip install mkdocs
      - name: Deploy docs
        run: mkdocs gh-deploy
